// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';
import YouTubeEmbed from './YouTubeEmbed';

export {
	Hero,
	Image,
	ImageCards,
	Quote,
	Text,
	TextWithImage,
	YouTubeEmbed,
};

export const components = {
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
	you_tube_embed: YouTubeEmbed,
};
